"""played_at now have timezone (GameHistory)

Revision ID: 121e824c9db0
Revises: 2b8a90c40b7f
Create Date: 2025-08-30 23:24:38.702463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "121e824c9db0"
down_revision: Union[str, None] = "2b8a90c40b7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
