"""decimials for bets, withrawns, games_history; extra_data field for games_history

Revision ID: 15a7f62e8072
Revises: 121e824c9db0
Create Date: 2025-09-07 16:49:51.427655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15a7f62e8072"
down_revision: Union[str, None] = "121e824c9db0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games_history", sa.Column("extra_data", sa.JSON(), nullable=False))
    op.alter_column(
        "games_history",
        "bet",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "games_history",
        "income",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=12, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "total_deposit",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=12, scale=2),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "total_withdrawn",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=12, scale=2),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "total_withdrawn",
        existing_type=sa.DECIMAL(precision=12, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "users",
        "total_deposit",
        existing_type=sa.DECIMAL(precision=12, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "games_history",
        "income",
        existing_type=sa.DECIMAL(precision=12, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "games_history",
        "bet",
        existing_type=sa.DECIMAL(precision=12, scale=2),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("games_history", "extra_data")
    # ### end Alembic commands ###
