"""bonuses

Revision ID: 17e0a2699488
Revises: fa284ffa4280
Create Date: 2025-10-03 15:19:03.516876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17e0a2699488'
down_revision: Union[str, None] = 'fa284ffa4280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonus_type', sa.String(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('deposit_bonus_multiplier', sa.DECIMAL(precision=6, scale=2), server_default='1.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deposit_bonus_multiplier')
    op.drop_table('bonuses')
    # ### end Alembic commands ###
