"""added field bet to HistoryGames

Revision ID: 2b8a90c40b7f
Revises: 791be9b604e7
Create Date: 2025-08-30 21:32:39.641905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8a90c40b7f'
down_revision: Union[str, None] = '791be9b604e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_history', sa.Column('bet', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games_history', 'bet')
    # ### end Alembic commands ###
