"""add game and tag models, some columns fixed

Revision ID: 3a63d5ad23a5
Revises: ede98c47170c
Create Date: 2025-06-16 19:18:49.798429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a63d5ad23a5'
down_revision: Union[str, None] = 'ede98c47170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_tags',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    op.add_column('games', sa.Column('photo', sa.String(), server_default='/defaultGamePic.png', nullable=False))
    op.create_unique_constraint(None, 'games', ['name'])
    op.alter_column('users', 'photo',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'photo',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'photo')
    op.drop_table('game_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
