"""deleted users relationship super_bonuses = relationship('Bonuse')

Revision ID: 41c4ae10ff29
Revises: 4679afcbb7d8
Create Date: 2025-10-05 15:31:10.836936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c4ae10ff29'
down_revision: Union[str, None] = '4679afcbb7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
