"""is_super_bonuse field in Bonuse

Revision ID: 4679afcbb7d8
Revises: 17e0a2699488
Create Date: 2025-10-05 00:29:53.756524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4679afcbb7d8'
down_revision: Union[str, None] = '17e0a2699488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonuses', sa.Column('is_super_bonuse', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonuses', 'is_super_bonuse')
    # ### end Alembic commands ###
