"""fix game-tag relationship

Revision ID: 6eb1f093dea7
Revises: 3a63d5ad23a5
Create Date: 2025-06-16 19:53:07.180772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb1f093dea7'
down_revision: Union[str, None] = '3a63d5ad23a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
