"""site_statistics table

Revision ID: fa284ffa4280
Revises: 15a7f62e8072
Create Date: 2025-09-16 16:15:21.494968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa284ffa4280"
down_revision: Union[str, None] = "15a7f62e8072"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "total_earned",
            sa.DECIMAL(precision=17, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("total_played", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "total_earned_today",
            sa.DECIMAL(precision=15, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "users",
        sa.Column(
            "total_earned",
            sa.DECIMAL(precision=17, scale=2),
            server_default="0.00",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("total_played", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "total_played")
    op.drop_column("users", "total_earned")
    op.drop_table("site_statistics")
    # ### end Alembic commands ###
